apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-28T09:30:17Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3065"
  uid: d020f77f-81ca-4e53-a8d6-3e142b1cc037
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.161.139
  clusterIPs:
  - 10.102.161.139
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30171
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
